[ECO-371] Add cart rule support
mobbexco/prestashop-marketplace pull request #12
Opened 2023-06-21 14:25 UTC by mobbexLuis

2023-09-05 14:26 UTC, EMunozMobbex approved these changes

2023-10-20 04:18 UTC, jlmobbex requested changes

2023-10-20 04:18 UTC, jlmobbex commented on mobbex_marketplace/mobbex_marketplace.php
> +                    'total'       => !$cart->getCartRules() ? $item['total_wt'] : $item['price_wt'],
PrestaShop podría estar volviendo a buscar cada cartRule al momento de llamar este método. Me parece más eficiente ponerlo afuera de ambos foreachs. Sino se va a ejecutar por cada item de cada vendor, y siempre va a valer lo mismo.

2023-10-20 04:18 UTC, jlmobbex commented on mobbex_marketplace/Models/Helper.php
> +        return $vendors;
- Este método devuelve los productos ordenados por vendor, pero no se menciona esto en el nombre del mismo (a diferencia de `getProductVendor`). No sería mejor que este sólo devuelva los productos con el precio calculado y que después si se desea se ordena usando el otro método desde fuera? De esta forma cada método se encarga de una sóla función.
- Este método se puede simplificar bastante. Creo que queda más fácil de entender del siguiente modo:
```php
public static function getCartProducts($cart)
{
    $priceCalculator = new \Mobbex\PS\Checkout\Models\PriceCalculator($cart);
    
    return self::getProductsVendors(
        $cart->getCartRules() ? $priceCalculator->getCartRules() : $cart->getProducts(true)
    );
}
```

2023-10-23 15:44 UTC, mobbexLuis commented on mobbex_marketplace/mobbex_marketplace.php
> +                    'total'       => !$cart->getCartRules() ? $item['total_wt'] : $item['price_wt'],
Despues de analizarlo y hacer un seguimiento del flujo me di cuenta que no hacia falta hacer esa comprobación directamente. Simplemente se llama a la posición del producto que se ve afectada por los cambios de precio en caso de que haya cart rules. En caso que no existan, el precio de esa posicioon es el original.
Comento para que quede un poco mas claro

2023-10-23 20:39 UTC, jlmobbex approved these changes

2023-10-23 20:39 UTC, merged